# Generated by Django 5.1.1 on 2024-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('F', 'Failed'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
    ]
